[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "dotnet GetEmpStatus.dll"
healthcheckPath = "/api/employee/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10